Module7 task2
htmlacademy-javascript/852159-kekstagram-25 pull request #7
Opened 2022-04-12 21:07 UTC by badflamingo

Сделала сразу 2 задания, не знаю как правильно оформить пулл реквест. Надеюсь все правильно :)

2022-04-13 13:06 UTC, KHarpushkina commented on js/render-fullsize-picture.js
> +    if (event.key === 'Enter') {
Для чего нужен этот обработчик? Что-то не нахожу в задание ничего про кнопку Enter

2022-04-13 13:06 UTC, KHarpushkina commented on js/render-fullsize-picture.js
> +function renderFullsize(posts) {
Одна большая функция, внутри которой другие функции. Довольно тяжело читать и понимать. Нужно всё это дело разбить и структурировать. Вынеси другие функции из этой, помни про единообразие объявления функций и правильное их именование

2022-04-13 13:19 UTC, KHarpushkina commented
> Сделала сразу 2 задания, не знаю как правильно оформить пулл реквест. Надеюсь все правильно :)
> 
> 🎓 [Отрисуй меня полностью (часть 2)](https://up.htmlacademy.ru/javascript/25/user/852159/tasks/12)
> 
> 💥 https://htmlacademy-javascript.github.io/852159-kekstagram-25/7/

То есть тут ещё задание 14. Правда или действие (часть 1) ?

2022-04-15 15:57 UTC, ant1quar requested changes

2022-04-15 15:57 UTC, ant1quar commented on js/render-fullsize-picture.js
> +        <p class="social__text">${commentObject.message}</p>`;
Давай сделаем не текстом, а через create element и append

2022-04-16 12:45 UTC, badflamingo commented on js/render-fullsize-picture.js
> +        <p class="social__text">${commentObject.message}</p>`;
Внесла изменения и добавила сразу задания 8 и 9

2022-04-16 13:00 UTC, merged